[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "jetson"
version = "0.0.1"
description = "JetsonNano"
authors = [
  { name = "Rudobrody" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "==3.11.5"


[tool.ruff]
line-length = 99
src = ["jetson"]
include = ["pyproject.toml", "jetson/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["jetson"]
force-sort-within-sections = true

